# Generated by Django 5.0.5 on 2024-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('availabilityStatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
