# Generated by Django 5.0.5 on 2024-07-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to='cart_images/'),
        ),
    ]
