# Generated by Django 5.0.5 on 2024-07-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_image_remove_cart_name_remove_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='cart_products/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
