# Generated by Django 5.0.5 on 2024-07-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_product_img_cart_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
    ]
